import Head from 'next/head';
import '../globals.css';

import { DbProvider } from '@/data/DbProvider';

const PWA = {
  url: 'https://sso-log.lara.horse',
  name: 'SSO-log.lara.horse',
  description: 'log all your SSO horses',
  themeColor: '#7f22fe',
  backgroundColor: '#0a0a0a',
} as const;

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export default function RootLayout({ Component, pageProps }: any) {
  return (
    <>
      <Head>
        <title>sso-log.lara.horse</title>
        <meta name="description" content="Generated by Julie Eveningrock" />
        <link rel="icon" href="/favicon-196.png" />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no, user-scalable=no, viewport-fit=cover"
        />

        <meta name="application-name" content={PWA.name} />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content={PWA.name} />
        <meta name="description" content={PWA.description} />
        <meta name="format-detection" content="telephone=no" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="msapplication-config" content="/icons/browserconfig.xml" />
        <meta name="msapplication-TileColor" content={PWA.themeColor} />
        <meta name="msapplication-tap-highlight" content="no" />
        <meta name="theme-color" content={PWA.backgroundColor} />

        <link rel="apple-touch-icon" href="/icons/touch-icon-iphone.png" />
        <link rel="apple-touch-icon" sizes="152x152" href="/icons/touch-icon-ipad.png" />
        <link rel="apple-touch-icon" sizes="180x180" href="/icons/touch-icon-iphone-retina.png" />
        <link rel="apple-touch-icon" sizes="167x167" href="/icons/touch-icon-ipad-retina.png" />

        <link rel="icon" type="image/png" sizes="32x32" href="/icons/favicon-196.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/icons/favicon-196.png" />
        <link rel="manifest" href="/manifest.json" />
        <link rel="mask-icon" href="/icons/safari-pinned-tab.svg" color={PWA.themeColor} />
        <link rel="shortcut icon" href="/favicon-196.png" />

        <meta property="og:type" content="website" />
        <meta property="og:title" content={PWA.name} />
        <meta property="og:site_name" content={PWA.name} />
        <meta property="og:description" content={PWA.description} />
        <meta property="og:url" content={PWA.url} />
        <meta property="og:image" content={`${PWA.url}/icons/apple-touch-icon.png`} />
      </Head>

      <main>
        <DbProvider>
          <Component {...pageProps} />
        </DbProvider>
      </main>
    </>
  );
}
