import Head from 'next/head';
import '../globals.css';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export default function RootLayout({ Component, pageProps }: any) {
  return (
    <>
      <Head>
        <title>sso-log.lara.horse</title>
        <meta name="description" content="Generated by Julie Eveningrock" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Component {...pageProps} />
      </main>
    </>
  );
}
